name: boom_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy=2.3.3
  - pandas=2.3.2
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - pyarrow=21.0.0
  - fastparquet=2024.11.0
  - jupyterlab
  - ipykernel=6.30.1
  - tornado=6.5.2
  - psutil=7.1.0
  - pyzmq=27.1.0
  - pillow=11.3.0
  - fonttools=4.60.0
  - packaging=25.0
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - tzdata=2025b
  - joblib=1.5.2
  - threadpoolctl=3.6.0
  - kiwisolver=1.4.9
  - contourpy=1.3.3
  - colorama=0.4.6
  - cycler=0.12.1
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - six=1.17.0
  - typing-extensions=4.15.0
  - platformdirs=4.4.0

  - pip
  - pip:
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - ipython==9.5.0
      - asttokens==3.0.0
      - comm==0.2.3
      - cramjam==2.11.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - fsspec==2025.9.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - parso==0.8.5
      - prompt-toolkit==3.0.52
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.4
      - pywin32==311
      - stack-data==0.6.3
      - traitlets==5.14.3
      - wcwidth==0.2.13
